default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  encoding: utf8
  database: <%= ENV['POSTGRES_ENV_POSTGRESQL_DB'] %>
  pool: 5
  username: <%= ENV['POSTGRES_ENV_POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRES_ENV_POSTGRESQL_PASS'] %>
